class LangData{
  String name;
  String engName;
  String image;
  bool current;
  int id;
  LangData({this.name, this.engName, this.image, this.current, this.id});
}

class Lang {

  static var english = 1;
  static var german = 2;
  static var espanol = 3;

  List<LangData> langData = [
    LangData(name: "English", engName: "English", image: "assets/usa.png", current: false, id: english),
    LangData(name: "German", engName: "Deutsh", image: "assets/ger.png", current: false, id: german),
    LangData(name: "Spanish", engName: "Spana", image: "assets/esp.png", current: false, id: espanol),
  ];

  Map<int, String> langDeu = {
    0 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    2 : "Lorem ipsum",
    3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ",
    10: "Food Delivery Flutter App UI Kit",
    11: "Überspringen",
    12: "Down",
    13: "Beginnen wir mit LogIn!",
    14: "Geben Sie Ihre Anmeldedaten ein, um auf Ihr Konto zuzugreifen.",
    15: "Login",
    16: "Passwort",
    17: "Passwort vergessen",
    18: "Weiter",
    19: "Sie haben noch kein Konto? Erstellen",
    20: "Passwort vergessen",
    21: "E-Mail-Adresse",
    22: "LOGIN",
    23: "SENDEN",
    24: "Konto erstellen!",
    25: "Passwort bestätigen",
    26: "KONTO ERSTELLEN",
    27: "Um fortzufahren, geben Sie Ihre Telefonnummer ein",
    28: "Telefonnummer",
    29: "WEITER",
    30: "Telefonnummer überprüfen",
    31: "Fast fertig!",
    32: "Codeüberprüfung erfolgreich !!!",
    33: "Zuhause",
    34: "Suche",
    35: "Benachrichtigungen",
    36: "Meine Bestellungen",
    37: "Konto",
    38: "Favoriten",
    39: "Top Restaurants",
    40: "Trend diese Woche",
    41: "Lebensmittelkategorien",
    42: "Am beliebtesten",
    43: "Aktuelle Bewertungen",
    44: "Keine Benachrichtigungen haben",
    45: "Benachrichtigungen",
    46: "Wischen Sie die Benachrichtigung nach links, um sie zu löschen",
    47: "Karte",
    48: "Adresse",
    49: "Zahlung",
    50: "Geschichte",
    51: "Hilfe & Support",
    52: "Unbezahlt",
    53: "Versand",
    54: "Versand",
    55: "In Streit",
    56: "Bestellliste",
    57: "Benutzername",
    58: "E-Mail",
    59: "Telefon",
    60: "Geschlecht",
    61: "Geburtsdatum",
    62: "Sprachen",
    63: "App-Sprache",
    64: "Produkte",
    65: "Dienste",
    66: "Lieferung",
    67: "Verschiedenes",
    68: "Dienstzeit",
    69: "Information",
    70: "Montag",
    71: "Dienstag",
    72: "Mittwoch",
    73: "Donnerstag",
    74: "Freitag",
    75: "Samstag",
    76: "Sonntag",
    77: "Bewertungen",
    78: "Siehe auch",
    79: "Zutaten",
    80: "Ernährung",
    81: "Kalorien",
    82: "Gesamtfett",
    83: "Zucker",
    84: "Calcium",
    85: "Vitamin D",
    86: "Protein",
    87: "Cholesterin",
    88: "Eisen",
    89: "Extras",
    90: "In den Warenkorb",
    91: "Gerichte",
    92: "Menü",
    93: "Zwischensumme",
    94: "Einkaufskosten",
    95: "Steuern",
    96: "Gesamt",
    97: "Kasse",
    98: "Korb",
    99: "Einkaufswagen",
    100: "Überprüfen Sie Ihre Menge und klicken Sie auf Kasse",
    101: "Lieferadresse",
    102: "Adresse 1",
    103: "Adresse 2",
    104: "Stadt",
    105: "E-Mail-Adresse",
    106: "Telefon",
    107: "Weiter",
    108: "Kredit- / Debitkarte",
    109: "Nachnahme",
    110: "PayPal",
    111: "Google Wallet",
    112: "Zahlung",
    113: "Methoden",
    114: "Wählen Sie Ihre Zahlungsmethode",
    115: "Bezahlen",
    116: "Erfolg",
    117: "Sie erhalten Zahlung an den Verkäufer",
    118: "Fertig",
    119: "Meine Bestellungen",
    120: "Bestellung aufgegeben",
    121: "Zahlungsüberprüfung",
    122: "Verarbeitung",
    123: "Unterwegs",
    124: "Lieferung",
    125 : "Comments",
    126: "Sie erhalten eine Zahlung an den Verkäufer",
    127: "Passwort ändern",
    128: "Profil bearbeiten",
    129: "Altes Passwort",
    130: "Geben Sie Ihr altes Passwort ein",
    131: "Neues Passwort",
    132: "Geben Sie Ihr neues Passwort ein",
    133: "Neues Passwort bestätigen",
    134: "Geben Sie Ihr neues Passwort ein",
    135: "Abbrechen",
    136: "Profil bearbeiten",
    137: "Benutzername",
    138: "Geben Sie Ihren Benutzernamen ein",
    139: "E-Mail",
    140: "Geben Sie Ihre Benutzer-E-Mail-Adresse ein",
    141: "Geben Sie Ihr Benutzertelefon ein",
    142: "Ändern",
    143: "Galerie öffnen",
    144: "Kamera öffnen",
    145: "Passwort ändern",
  };

  Map<int, String> langEsp = {
    0 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    2 : "Lorem ipsum",
    3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ",
    10: "Kit de interfaz de usuario de la aplicación Flutter de entrega de alimentos",
    11: "Omitir",
    12: "Abajo",
    13: "¡Empecemos con Iniciar sesión!",
    14: "Ingrese sus datos de inicio de sesión para acceder a su cuenta",
    15: "Iniciar sesión",
    16: "Contraseña",
    17: "Contraseña olvidada",
    18: "Continuar",
    19: "¿No tienes una cuenta? Crear",
    20: "Contraseña olvidada",
    21: "Dirección de correo electrónico",
    22: "INICIAR SESIÓN",
    23: "ENVIAR",
    24: "¡Crea una cuenta!",
    25: "Confirmar contraseña",
    26: "CREAR CUENTA",
    27: "Para continuar ingrese su número de teléfono",
    28: "Número de teléfono",
    29: "CONTINUAR",
    30: "Verificar número de teléfono",
    31: "¡Casi terminado!",
    32: "¡Verificación de código exitosa!",
    33: "Inicio",
    34: "Buscar",
    35: "Notificaciones",
    36: "Mis pedidos",
    37: "Cuenta",
    38: "Favoritos",
    39: "Mejores restaurantes",
    40: "Tendencias de esta semana",
    41: "Categorías de alimentos",
    42: "Más popular",
    43: "Reseñas recientes",
    44: "No tener notificaciones",
    45: "Notificaciones",
    46: "Desliza hacia la izquierda la notificación para eliminarla",
    47: "Mapa",
    48: "Dirección",
    49: "Pago",
    50: "Historia",
    51: "Ayuda y soporte",
    52: "Sin pagar",
    53: "Enviado",
    54: "Para enviar",
    55: "En disputa",
    56: "Lista de pedidos",
    57: "Nombre de usuario",
    58: "Correo electrónico",
    59: "Teléfono",
    60: "Género",
    61: "Fecha de nacimiento",
    62: "Idiomas",
    63: "Idioma de la aplicación",
    64: "Productos",
    65: "Servicios",
    66: "Entrega",
    67: "Varios",
    68: "Duración del servicio",
    69: "Información",
    70: "Lunes",
    71: "martes",
    72: "miércoles",
    73: "jueves",
    74: "Viernes",
    75: "sábado",
    76: "Domingo",
    77: "Reseñas",
    78: "Ver también",
    79: "Ingredientes",
    80: "Nutrición",
    81: "Calorías",
    82: "Grasa total",
    83: "Azúcares",
    84: "Calcio",
    85: "Vitamina D",
    86: "Proteína",
    87: "Colesterol",
    88: "Hierro",
    89: "Extras",
    90: "Añadir al carrito",
    91: "Platos",
    92: "Menú",
    93: "Subtotal",
    94: "Costos de compra",
    95: "Impuestos",
    96: "Total",
    97: "Pagar",
    98: "Cesta",
    99: "Carrito de la compra",
    100: "Verifique su cantidad y haga clic en pagar",
    101: "Dirección de entrega",
    102: "Dirección 1",
    103: "Dirección 2",
    104: "Ciudad",
    105: "Dirección de correo electrónico",
    106: "Teléfono",
    107: "Siguiente",
    108: "Tarjeta de crédito / débito",
    109: "Pago contra reembolso",
    110: "PayPal",
    111: "Google Wallet",
    112: "Pago",
    113: "Métodos",
    114: "Elija su método de pago",
    115: "Pagar",
    116: "Éxito",
    117: "Usted recibe el pago al vendedor",
    118: "Listo",
    119: "Mis pedidos",
    120: "Pedido realizado",
    121: "Verificación de pago",
    122: "Procesando",
    123: "En camino",
    124: "Entrega",
    125 : "Comments",
    126: "Usted recibe el pago al vendedor",
    127: "Cambiar contraseña",
    128: "Editar perfil",
    129: "Contraseña anterior",
    130: "Ingrese su contraseña anterior",
    131: "Nueva contraseña",
    132: "Ingrese su nueva contraseña",
    133: "Confirmar nueva contraseña",
    134: "Ingrese su nueva contraseña",
    135: "Cancelar",
    136: "Editar perfil",
    137: "Nombre de usuario",
    138: "Introduzca su nombre de usuario",
    139: "Correo electrónico",
    140: "Ingrese su correo electrónico de usuario",
    141: "Ingrese su teléfono de usuario",
    142: "Cambiar",
    143: "Abrir galería",
    144: "Cámara abierta",
    145: "Cambiar contraseña",
  };

  Map<int, String> langEng = {
    0 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    2 : "Lorem ipsum",
    3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ",
    10 : "Food Delivery Flutter App UI Kit",
    11 : "Skip",
    12 : "Down",
    13 : "Let's start with LogIn!",
    14 : "Enter you login details to access your account.",
    15 : "Login",
    16 : "Password",
    17 : "Forgot password",
    18 : "Continue",
    19 : "Don't have an account? Create",
    20 : "Forgot password",
    21 : "E-mail address",
    22 : "LOGIN",
    23 : "SEND",
    24 : "Create an Account!",
    25 : "Confirm Password",
    26 : "CREATE ACCOUNT",
    27 : "To continue enter your phone number",
    28 : "Phone number",
    29 : "CONTINUE",
    30 : "Verify phone number",
    31 : "Almost done!",
    32 : "Code verification success!!!",
    33 : "Home",
    34 : "Search",
    35 : "Notifications",
    36 : "My Orders",
    37 : "Account",
    38 : "Favorites",
    39 : "Top Restaurants",
    40 : "Trending this week",
    41 : "Food categories",
    42 : "Most Popular",
    43 : "Recent Reviews",
    44 : "Not Have Notifications",
    45 : "Notifications",
    46 : "This is very important information",
    47 : "Map",
    48 : "Address",
    49 : "Payment",
    50 : "History",
    51 : "Help & support",
    52 : "Unpaid",
    53 : "Shipped",
    54 : "To be Shipped",
    55 : "In Dispute",
    56 : "Orders List",
    57 : "Username",
    58 : "E-mail",
    59 : "Phone",
    60 : "Gender",
    61 : "Date of birth",
    62 : "Languages",
    63 : "App Language",
    64 : "Products",
    65 : "Services",
    66 : "Delivery",
    67 : "Misc",
    68 : "Term of service",
    69 : "Information",
    70 : "Monday",
    71 : "Tuesday",
    72 : "Wednesday",
    73 : "Thursday",
    74 : "Friday",
    75 : "Saturday",
    76 : "Sunday",
    77 : "Reviews",
    78 : "See Also",
    79 : "Ingredients",
    80 : "Nutrition",
    81 : "Calories",
    82 : "Total Fat",
    83 : "Sugars",
    84 : "Calcium",
    85 : "Vitamin D",
    86 : "Protein",
    87 : "Cholesterol",
    88 : "Iron",
    89 : "Extras",
    90 : "Add to cart",
    91 : "Dishes",
    92 : "Menu",
    93 : "Subtotal",
    94 : "Shopping costs",
    95 : "Taxes",
    96 : "Total",
    97 : "Checkout",
    98 : "Basket",
    99 : "Shopping Cart",
    100 : "Verify your quantity and click checkout",
    101 : "Delivery Address",
    102 : "Address 1",
    103 : "Address 2",
    104 : "City",
    105 : "Email address",
    106 : "Phone",
    107 : "Next",
    108 : "Credit/Debit Card",
    109 : "Cash On Delivery",
    110 : "PayPal",
    111 : "Google Wallet",
    112 : "Payment",
    113 : "Methods",
    114 : "Choose your payment method",
    115 : "Pay",
    116 : "Success",
    117 : "You Payment Receive to Seller",
    118 : "Done",
    119 : "My Orders",
    120 : "Order placed",
    121 : "Payment verification",
    122 : "Processing",
    123 : "On the way",
    124 : "Delivery",
    125 : "Comments",
    126 : "You Payment Receive to Seller",
    127 : "Change password",
    128 : "Edit profile",
    129 : "Old password",
    130 : "Enter your old password",
    131 : "New password",
    132 : "Enter your new password",
    133 : "Confirm New password",
    134 : "Enter your new password",
    135 : "Cancel",
    136 : "Edit profile",
    137 : "User Name",
    138 : "Enter your User Name",
    139 : "E-mail",
    140 : "Enter your User E-mail",
    141 : "Enter your User Phone",
    142 : "Change",
    143 : "Open Gallery",
    144 : "Open Camera",
    145 : "Change password",

  };

  //
  //
  //
  setLang(int id){
    if (id == english) {
      defaultLang = langEng;
      init = true;
    }
    if (id == german) {
      defaultLang = langDeu;
      init = true;
    }
    if (id == espanol) {
      defaultLang = langEsp;
      init = true;
    }for (var lang in langData) {
      lang.current = false;
      if (lang.id == id)
        lang.current = true;
    }
  }

  Map<int, String> defaultLang;
  var init = false;

  String get(int id){
    if (!init) return "";
    return defaultLang[id];
  }

}

